import { dayOfYear } from '$lib/utils/dates.js';

interface Quote {
	text: string;
	author: string;
}

const QUOTES: Quote[] = [
	{ text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
	{ text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
	{ text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
	{ text: 'Life is what happens when you\'re busy making other plans.', author: 'John Lennon' },
	{ text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
	{ text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
	{ text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky' },
	{ text: 'Whether you think you can or think you can\'t, you\'re right.', author: 'Henry Ford' },
	{ text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb' },
	{ text: 'An unexamined life is not worth living.', author: 'Socrates' },
	{ text: 'Spread love everywhere you go. Let no one ever come to you without leaving happier.', author: 'Mother Teresa' },
	{ text: 'When you reach the end of your rope, tie a knot in it and hang on.', author: 'Franklin D. Roosevelt' },
	{ text: 'Always remember that you are absolutely unique. Just like everyone else.', author: 'Margaret Mead' },
	{ text: 'Don\'t judge each day by the harvest you reap but by the seeds that you plant.', author: 'Robert Louis Stevenson' },
	{ text: 'The purpose of our lives is to be happy.', author: 'Dalai Lama' },
	{ text: 'Get busy living or get busy dying.', author: 'Stephen King' },
	{ text: 'You only live once, but if you do it right, once is enough.', author: 'Mae West' },
	{ text: 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas A. Edison' },
	{ text: 'You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.', author: 'Dr. Seuss' },
	{ text: 'If life were predictable it would cease to be life, and be without flavor.', author: 'Eleanor Roosevelt' },
	{ text: 'If you look at what you have in life, you\'ll always have more.', author: 'Oprah Winfrey' },
	{ text: 'If you want to live a happy life, tie it to a goal, not to people or things.', author: 'Albert Einstein' },
	{ text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
	{ text: 'Money and success don\'t change people; they merely amplify what is already there.', author: 'Will Smith' },
	{ text: 'Your time is limited, so don\'t waste it living someone else\'s life.', author: 'Steve Jobs' },
	{ text: 'Not how long, but how well you have lived is the main thing.', author: 'Seneca' },
	{ text: 'If life is not smiling at you, give it a good tickling.', author: 'Unknown' },
	{ text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins' },
	{ text: 'In this life we cannot do great things. We can only do small things with great love.', author: 'Mother Teresa' },
	{ text: 'Only a life lived for others is a life worthwhile.', author: 'Albert Einstein' },
	{ text: 'The journey of a thousand miles begins with one step.', author: 'Lao Tzu' },
	{ text: 'It is during our darkest moments that we must focus to see the light.', author: 'Aristotle' },
	{ text: 'Whoever is happy will make others happy too.', author: 'Anne Frank' },
	{ text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
	{ text: 'You will face many defeats in life, but never let yourself be defeated.', author: 'Maya Angelou' },
	{ text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
	{ text: 'In the end, it\'s not the years in your life that count. It\'s the life in your years.', author: 'Abraham Lincoln' },
	{ text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
	{ text: 'Life is either a daring adventure or nothing at all.', author: 'Helen Keller' },
	{ text: 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.', author: 'Thomas A. Edison' },
	{ text: 'You have power over your mind, not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius' },
	{ text: 'The mind is everything. What you think you become.', author: 'Buddha' },
	{ text: 'Happiness is not something ready made. It comes from your own actions.', author: 'Dalai Lama' },
	{ text: 'If you are working on something that you really care about, you don\'t have to be pushed. The vision pulls you.', author: 'Steve Jobs' },
	{ text: 'People who are crazy enough to think they can change the world, are the ones who do.', author: 'Rob Siltanen' },
	{ text: 'We may encounter many defeats but we must not be defeated.', author: 'Maya Angelou' },
	{ text: 'Knowing is not enough; we must apply. Wishing is not enough; we must do.', author: 'Johann Wolfgang von Goethe' },
	{ text: 'Imagine your life is perfect in every respect; what would it look like?', author: 'Brian Tracy' },
	{ text: 'We generate fears while we sit. We overcome them by action.', author: 'Dr. Henry Link' },
	{ text: 'Whether you think you can or think you can\'t, you\'re right.', author: 'Henry Ford' },
	{ text: 'Security is mostly a superstition. Life is either a daring adventure or nothing.', author: 'Helen Keller' },
	{ text: 'The man who has confidence in himself gains the confidence of others.', author: 'Hasidic Proverb' },
	{ text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
	{ text: 'Innovation distinguishes between a leader and a follower.', author: 'Steve Jobs' },
	{ text: 'Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.', author: 'Steve Jobs' },
	{ text: 'You can\'t connect the dots looking forward; you can only connect them looking backwards.', author: 'Steve Jobs' },
	{ text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair' },
	{ text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
	{ text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
	{ text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
	{ text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
	{ text: 'Success is not how high you have climbed, but how you make a positive difference to the world.', author: 'Roy T. Bennett' },
	{ text: 'When we strive to become better than we are, everything around us becomes better too.', author: 'Paulo Coelho' },
	{ text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar' },
	{ text: 'The real test is not whether you avoid this failure, because you won\'t. It\'s whether you let it harden or shame you into inaction.', author: 'Barack Obama' },
	{ text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
	{ text: 'To see what is right and not do it is a lack of courage.', author: 'Confucius' },
	{ text: 'Reading is to the mind, as exercise is to the body.', author: 'Brian Tracy' },
	{ text: 'Opportunity is missed by most people because it is dressed in overalls and looks like work.', author: 'Thomas Edison' },
	{ text: 'A successful man is one who can lay a firm foundation with the bricks others have thrown at him.', author: 'David Brinkley' },
	{ text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
	{ text: 'I have learned over the years that when one\'s mind is made up, this diminishes fear.', author: 'Rosa Parks' },
	{ text: 'I alone cannot change the world, but I can cast a stone across the water to create many ripples.', author: 'Mother Teresa' },
	{ text: 'Nothing is impossible, the word itself says \'I\'m possible\'!', author: 'Audrey Hepburn' },
	{ text: 'The question isn\'t who is going to let me; it\'s who is going to stop me.', author: 'Ayn Rand' },
	{ text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
	{ text: 'It\'s not whether you get knocked down, it\'s whether you get up.', author: 'Vince Lombardi' },
	{ text: 'People often say that motivation doesn\'t last. Well, neither does bathing. That\'s why we recommend it daily.', author: 'Zig Ziglar' },
	{ text: 'There is nothing permanent except change.', author: 'Heraclitus' },
	{ text: 'You must be the change you wish to see in the world.', author: 'Mahatma Gandhi' },
	{ text: 'Spread love everywhere you go.', author: 'Mother Teresa' },
	{ text: 'When you reach the end of your rope, tie a knot in it and hang on.', author: 'Franklin D. Roosevelt' }
];

export function getQuoteOfTheDay(): Quote {
	const index = dayOfYear() % QUOTES.length;
	return QUOTES[index];
}
